# Generated by Django 2.2.5 on 2022-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
