# Generated by Django 2.2.5 on 2022-03-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='detail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profession',
            name='detail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.College'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Profession'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tell',
            field=models.CharField(default='', max_length=12),
        ),
    ]
