# Generated by Django 2.2.5 on 2022-03-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20220317_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
