# Generated by Django 2.2.5 on 2022-03-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220317_1637'),
        ('teacher', '0005_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(default='', max_length=20)),
                ('week', models.CharField(default='', max_length=20)),
                ('day', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('course_name', models.CharField(default='', max_length=250)),
                ('teacher_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
