# Generated by Django 2.2.5 on 2022-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profession',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
