# Generated by Django 2.2.5 on 2022-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220317_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wx_uid',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
