# Generated by Django 2.2.5 on 2022-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220318_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
