# Generated by Django 2.2.5 on 2022-03-17 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher_account',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 53, 26, 629976)),
        ),
    ]
