# Generated by Django 2.2.5 on 2022-03-17 11:42

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0002_auto_20220317_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_account', models.CharField(default='', max_length=250)),
                ('invigilate_state', models.CharField(choices=[(0, '未确认'), (1, '已同意'), (2, '反对监考')], default='男', max_length=1)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='arrange.Exam')),
            ],
        ),
    ]
