# Generated by Django 2.2.5 on 2022-03-17 12:02

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0003_auto_20220317_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='teacher_account',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='account.Account'),
        ),
    ]
