# Generated by Django 2.2.5 on 2022-03-17 12:11

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220317_1637'),
        ('arrange', '0004_auto_20220317_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField(max_length=25000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('teacher_account', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='account.Account')),
            ],
        ),
    ]
