# Generated by Django 2.2.5 on 2022-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
