# Generated by Django 2.2.5 on 2022-03-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0007_exam_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='collage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.College'),
        ),
    ]
