# Generated by Django 2.2.5 on 2022-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0009_auto_20220319_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
