# Generated by Django 2.2.5 on 2022-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0010_auto_20220319_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
