# Generated by Django 2.2 on 2022-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0011_auto_20220319_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='invigilate_state',
            field=models.IntegerField(choices=[(0, '未确认'), (1, '已同意'), (2, '反对监考')], default=0, max_length=1),
        ),
    ]
