# Generated by Django 2.2 on 2022-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrange', '0012_auto_20220320_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrange',
            name='invigilate_state',
            field=models.IntegerField(choices=[(0, '未确认'), (1, '已同意'), (2, '反对监考')], default=0),
        ),
    ]
